import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
// import type { paths } from "./lib/api/v1"; // generated by openapi-typescript
import type { paths } from "./lib/api/my-openapi-3-schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
	baseUrl: "https://myapi.dev/v1/",
});

const $api = createClient(fetchClient);

const MyComponent = () => {
	const { data, error, isPending } = $api.useQuery(
		"get",
		"/blogposts/{post_id}",
		{
			params: {
				path: { post_id: 5 },
			},
		}
	);

	if (isPending || !data) return "Loading...";

	if (error) return `An error occurred: ${error.message}`;

	return <div>{data.title}</div>;
};